INSERT INTO report_field_catalog (
  report_type,
  field_key,
  field_label,
  field_group,
  data_type,
  supports_filter,
  supports_sort,
  is_default,
  default_order,
  select_expression,
  filter_expression,
  is_active
) VALUES
  ('reservation','id_guest','ID huesped','Huesped','number',1,1,0,30,'base.id_guest','base.id_guest',1),
  ('reservation','guest_names','Nombres huesped','Huesped','text',1,1,0,31,'base.guest_names','base.guest_names',1),
  ('reservation','guest_last_name','Apellido huesped','Huesped','text',1,1,0,32,'base.guest_last_name','base.guest_last_name',1),
  ('reservation','guest_phone','Telefono huesped','Huesped','text',1,1,0,33,'base.guest_phone','base.guest_phone',1),
  ('reservation','guest_nationality','Nacionalidad huesped','Huesped','text',1,1,0,34,'base.guest_nationality','base.guest_nationality',1),
  ('reservation','guest_country_residence','Pais residencia huesped','Huesped','text',1,1,0,35,'base.guest_country_residence','base.guest_country_residence',1),
  ('reservation','guest_language','Idioma huesped','Huesped','text',1,1,0,36,'base.guest_language','base.guest_language',1),
  ('reservation','id_rateplan','ID rateplan','Reservacion','number',1,1,0,37,'base.id_rateplan','base.id_rateplan',1),
  ('reservation','channel_ref','Canal referencia','Reservacion','text',1,1,0,38,'base.channel_ref','base.channel_ref',1),
  ('reservation','eta','ETA','Reservacion','text',1,1,0,39,'base.eta','base.eta',1),
  ('reservation','etd','ETD','Reservacion','text',1,1,0,40,'base.etd','base.etd',1),
  ('reservation','checkin_at','Checkin timestamp','Reservacion','datetime',1,1,0,41,'base.checkin_at','base.checkin_at',1),
  ('reservation','checkout_at','Checkout timestamp','Reservacion','datetime',1,1,0,42,'base.checkout_at','base.checkout_at',1),
  ('reservation','infants','Infantes','Reservacion','number',1,1,0,43,'base.infants','base.infants',1),
  ('reservation','deposit_due_cents','Deposito pendiente','Reservacion','money',1,1,0,44,'base.deposit_due_cents','base.deposit_due_cents',1),
  ('reservation','deposit_due_at','Fecha deposito','Reservacion','datetime',1,1,0,45,'base.deposit_due_at','base.deposit_due_at',1),
  ('reservation','hold_until','Hold hasta','Reservacion','datetime',1,1,0,46,'base.hold_until','base.hold_until',1),
  ('reservation','cancel_reason','Motivo cancelacion','Reservacion','text',1,1,0,47,'base.cancel_reason','base.cancel_reason',1),
  ('reservation','canceled_at','Cancelada el','Reservacion','datetime',1,1,0,48,'base.canceled_at','base.canceled_at',1),
  ('reservation','notes_guest','Notas huesped','Reservacion','text',1,0,0,49,'base.notes_guest','base.notes_guest',1),
  ('reservation','notes_internal','Notas internas','Reservacion','text',1,0,0,50,'base.notes_internal','base.notes_internal',1),
  ('reservation','room_id','ID habitacion','Hospedaje','number',1,1,0,60,'base.room_id','base.room_id',1),
  ('reservation','room_floor','Piso habitacion','Hospedaje','text',1,1,0,61,'base.room_floor','base.room_floor',1),
  ('reservation','room_building','Edificio habitacion','Hospedaje','text',1,1,0,62,'base.room_building','base.room_building',1),
  ('reservation','room_capacity_total','Capacidad habitacion','Hospedaje','number',1,1,0,63,'base.room_capacity_total','base.room_capacity_total',1),
  ('reservation','room_max_adults','Max adultos habitacion','Hospedaje','number',1,1,0,64,'base.room_max_adults','base.room_max_adults',1),
  ('reservation','room_max_children','Max menores habitacion','Hospedaje','number',1,1,0,65,'base.room_max_children','base.room_max_children',1),
  ('reservation','category_id','ID categoria habitacion','Hospedaje','number',1,1,0,66,'base.category_id','base.category_id',1),
  ('reservation','category_code','Codigo categoria habitacion','Hospedaje','text',1,1,0,67,'base.category_code','base.category_code',1),
  ('reservation','category_max_occupancy','Max ocupacion categoria','Hospedaje','number',1,1,0,68,'base.category_max_occupancy','base.category_max_occupancy',1),
  ('reservation','property_city','Ciudad propiedad','Hospedaje','text',1,1,0,69,'base.property_city','base.property_city',1),
  ('reservation','property_state','Estado propiedad','Hospedaje','text',1,1,0,70,'base.property_state','base.property_state',1),
  ('reservation','property_country','Pais propiedad','Hospedaje','text',1,1,0,71,'base.property_country','base.property_country',1),
  ('reservation','property_timezone','Timezone propiedad','Hospedaje','text',1,1,0,72,'base.property_timezone','base.property_timezone',1),
  ('reservation','property_currency','Moneda propiedad','Hospedaje','text',1,1,0,73,'base.property_currency','base.property_currency',1),

  ('line_item','line_item_reference','Referencia line item','Line item','text',1,1,0,30,'base.line_item_reference','base.line_item_reference',1),
  ('line_item','line_item_external_ref','Referencia externa line item','Line item','text',1,1,0,31,'base.line_item_external_ref','base.line_item_external_ref',1),
  ('line_item','line_item_method','Metodo line item','Line item','text',1,1,0,32,'base.line_item_method','base.line_item_method',1),
  ('line_item','line_item_notes','Notas line item','Line item','text',1,0,0,33,'base.line_item_notes','base.line_item_notes',1),
  ('line_item','paid_cents','Paid cents','Importe','money',1,1,0,34,'base.paid_cents','base.paid_cents',1),
  ('line_item','reservation_status','Estatus reservacion','Reservacion','text',1,1,0,34,'base.reservation_status','base.reservation_status',1),
  ('line_item','reservation_source','Origen reservacion','Reservacion','text',1,1,0,35,'base.reservation_source','base.reservation_source',1),
  ('line_item','check_in_date','Check-in','Reservacion','date',1,1,0,36,'base.check_in_date','base.check_in_date',1),
  ('line_item','check_out_date','Check-out','Reservacion','date',1,1,0,37,'base.check_out_date','base.check_out_date',1),
  ('line_item','nights','Noches','Reservacion','number',1,1,0,38,'base.nights','base.nights',1),
  ('line_item','adults','Adultos','Reservacion','number',1,1,0,39,'base.adults','base.adults',1),
  ('line_item','children','Menores','Reservacion','number',1,1,0,40,'base.children','base.children',1),
  ('line_item','infants','Infantes','Reservacion','number',1,1,0,41,'base.infants','base.infants',1),
  ('line_item','id_guest','ID huesped','Huesped','number',1,1,0,42,'base.id_guest','base.id_guest',1),
  ('line_item','guest_names','Nombres huesped','Huesped','text',1,1,0,43,'base.guest_names','base.guest_names',1),
  ('line_item','guest_last_name','Apellido huesped','Huesped','text',1,1,0,44,'base.guest_last_name','base.guest_last_name',1),
  ('line_item','guest_email','Email huesped','Huesped','text',1,1,0,45,'base.guest_email','base.guest_email',1),
  ('line_item','guest_phone','Telefono huesped','Huesped','text',1,1,0,46,'base.guest_phone','base.guest_phone',1),
  ('line_item','guest_nationality','Nacionalidad huesped','Huesped','text',1,1,0,47,'base.guest_nationality','base.guest_nationality',1),
  ('line_item','guest_country_residence','Pais residencia huesped','Huesped','text',1,1,0,48,'base.guest_country_residence','base.guest_country_residence',1),
  ('line_item','guest_language','Idioma huesped','Huesped','text',1,1,0,49,'base.guest_language','base.guest_language',1),
  ('line_item','id_room','ID habitacion','Hospedaje','number',1,1,0,50,'base.id_room','base.id_room',1),
  ('line_item','room_code','Codigo habitacion','Hospedaje','text',1,1,0,51,'base.room_code','base.room_code',1),
  ('line_item','room_name','Nombre habitacion','Hospedaje','text',1,1,0,52,'base.room_name','base.room_name',1),
  ('line_item','room_floor','Piso habitacion','Hospedaje','text',1,1,0,53,'base.room_floor','base.room_floor',1),
  ('line_item','room_building','Edificio habitacion','Hospedaje','text',1,1,0,54,'base.room_building','base.room_building',1),
  ('line_item','room_capacity_total','Capacidad habitacion','Hospedaje','number',1,1,0,55,'base.room_capacity_total','base.room_capacity_total',1),
  ('line_item','room_max_adults','Max adultos habitacion','Hospedaje','number',1,1,0,56,'base.room_max_adults','base.room_max_adults',1),
  ('line_item','room_max_children','Max menores habitacion','Hospedaje','number',1,1,0,57,'base.room_max_children','base.room_max_children',1),
  ('line_item','id_category','ID categoria','Hospedaje','number',1,1,0,58,'base.id_category','base.id_category',1),
  ('line_item','category_code','Codigo categoria','Hospedaje','text',1,1,0,59,'base.category_code','base.category_code',1),
  ('line_item','category_name_room','Categoria habitacion','Hospedaje','text',1,1,0,60,'base.category_name_room','base.category_name_room',1),
  ('line_item','category_max_occupancy','Max ocupacion categoria','Hospedaje','number',1,1,0,61,'base.category_max_occupancy','base.category_max_occupancy',1),
  ('line_item','property_city','Ciudad propiedad','Hospedaje','text',1,1,0,62,'base.property_city','base.property_city',1),
  ('line_item','property_state','Estado propiedad','Hospedaje','text',1,1,0,63,'base.property_state','base.property_state',1),
  ('line_item','property_country','Pais propiedad','Hospedaje','text',1,1,0,64,'base.property_country','base.property_country',1),
  ('line_item','property_timezone','Timezone propiedad','Hospedaje','text',1,1,0,65,'base.property_timezone','base.property_timezone',1),
  ('line_item','property_currency','Moneda propiedad','Hospedaje','text',1,1,0,66,'base.property_currency','base.property_currency',1),

  ('property','property_city','Ciudad propiedad','Hospedaje','text',1,1,0,20,'base.property_city','base.property_city',1),
  ('property','property_state','Estado propiedad','Hospedaje','text',1,1,0,21,'base.property_state','base.property_state',1),
  ('property','property_country','Pais propiedad','Hospedaje','text',1,1,0,22,'base.property_country','base.property_country',1),
  ('property','property_timezone','Timezone propiedad','Hospedaje','text',1,1,0,23,'base.property_timezone','base.property_timezone',1),
  ('property','property_currency','Moneda propiedad','Hospedaje','text',1,1,0,24,'base.property_currency','base.property_currency',1)
ON DUPLICATE KEY UPDATE
  field_label = VALUES(field_label),
  field_group = VALUES(field_group),
  data_type = VALUES(data_type),
  supports_filter = VALUES(supports_filter),
  supports_sort = VALUES(supports_sort),
  is_default = VALUES(is_default),
  default_order = VALUES(default_order),
  select_expression = VALUES(select_expression),
  filter_expression = VALUES(filter_expression),
  is_active = VALUES(is_active),
  updated_at = NOW();
